---
- name: Ensure dependencies are installed
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates

- name: Ensure additional dependenciers are installed
  ansible.builtin.apt:
    name:
      - gnupg

- name: Add Docker apt key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}]
      https://download.docker.com/linux/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} stable
    state: present
    update_cache: true

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Install docker-compose plugin
  ansible.builtin.apt:
    name:
      - docker-compose-plugin

- name: Install python3 pip
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip

- name: Install the docker-compose pip3 package
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose
