---
- name: Create pi-hole directory
  ansible.builtin.file:
    path: ~/pi-hole
    state: directory
    mode: 0755
  register: pi_hole_dir

- name: Copy compose file
  ansible.builtin.copy:
    src: files/pi-hole-compose.yml
    dest: "{{ pi_hole_dir.path }}/docker-compose.yml"
    mode: 0640

- name: Start pi-hole service
  community.docker.docker_compose:
    project_src: "{{ pi_hole_dir.path }}/"
    build: false

- name: Use local name server
  ansible.builtin.lineinfile:
    line: "name_servers=127.0.0.1"
    dest: "/etc/resolvconf.conf"
    regexp: "^#?name_servers="
  notify: Regenerate resolvconf
