---
version: "3.9"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 54:54/udp
      - 67:67/udp
      - 80:80/tcp
    environment:
      TZ: Europe/Berlin
      WEBPASSWORD: 'C%Aw5yw5J*aPQkHp'
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./dnsmasq:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  pihole-exporter:
    container_name: pihole-exporter
    image: ekofr/pihole-exporter
    ports:
      - 9617:9617
    environment:
      PIHOLE_HOSTNAME: pihole
      PIHOLE_PASSWORD: 'C%Aw5yw5J*aPQkHp'
    depends_on:
      - pihole
    restart: always
